{% set name = "point_cloud_utils" %}
{% set version = "0.19.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/fwilliams/point-cloud-utils/archive/{{ version }}.tar.gz
  sha256: b241c9609d5c08ae3887fbf5d3a2525182beb85d3452ec09952f681e27d94b21

build:
  number: 1
  script:
    - set "CMAKE_GENERATOR=NMake Makefiles"  # [win]
    - "{{ PYTHON }} -m pip install . --no-deps -vv --install-option=\"--exclude-arch\"" 
  skip: true  # [win and vc<14]
    
requirements:
  build:
    - {{ compiler('cxx') }}
    - git
    - cmake
    - openmp
  host:
    - python
    - pip
    - setuptools
    - numpy
    - scipy
    
  run:
    - python
    - {{ pin_compatible('numpy') }}
    - scipy
    - openmp

test:
  imports:
    - point_cloud_utils
  source_files:
    - tests/test_examples.py
    - data/cube_twist.obj
    - data/duplicated_pcloud.ply
  commands:
    - python tests/test_examples.py
    
about:
  home: http://github.com/fwilliams/point-cloud-utils
  license: GPL-2.0
  license_family: GPL
  license_file: LICENSE
  summary: 'A Python library for common tasks on 3D point clouds'


extra:
  recipe-maintainers:
    - fwilliams
