{% set name = "point_cloud_utils" %}
{% set version = "0.21.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/fwilliams/point-cloud-utils/archive/{{ version }}.tar.gz
  sha256: b32c4585216b3f634e5fef7f3ed8ae0a6f9d0f1b6335a073b7a38eff3686e1f9

build:
  number: 0
  script:
    - set "CMAKE_GENERATOR=NMake Makefiles"  # [win]
    - {{ PYTHON }} -m pip install . --no-deps -vv --install-option="--exclude-arch"
  skip: true  # [win and vc<14]

requirements:
  build:
    - {{ compiler('cxx') }}
    - git
    - cmake
    - openmp
  host:
    - python
    - pip
    - setuptools
    - numpy
    - scipy

  run:
    - python
    - {{ pin_compatible('numpy') }}
    - scipy
    - openmp

test:
  imports:
    - point_cloud_utils
  source_files:
    - tests/test_examples.py
    - data/cube_twist.obj
    - data/duplicated_pcloud.ply
  commands:
    - python tests/test_examples.py

about:
  home: http://github.com/fwilliams/point-cloud-utils
  license: GPL-2.0
  license_family: GPL
  license_file: LICENSE
  summary: A Python library for common tasks on 3D point clouds


extra:
  recipe-maintainers:
    - fwilliams
